### ISSUE TITLE
Set up notification system to ping us when benchmarks are done.

### ISSUE THREAD

**Issue by baxtersa** [plasma-umass/stopify-benchmarks#2]

**Comment by baxtersa** [comment]
Looks like we can use `mail` to do this. @rachitnigam , what email address do you want notifications?

**Comment by rachitnigam** [comment]
Isn't there a way to do this through slack?

**Comment by baxtersa** [comment]
There's a way to POST to an incoming web hook url, but I don't have permissions to enable this or find out what the url is to post to.

**Comment by rachitnigam** [comment]
Okay, I use rnigam@umass.edu

**Comment by rachitnigam** [comment]
The notification system should generate some sort of log containing the run params (transforms, languages, time taken)
